ALTER TABLE pension_goal
  ADD COLUMN IF NOT EXISTS target_monthly_income NUMERIC(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS inflation_rate NUMERIC(6,4) NOT NULL DEFAULT 0.03,
  ADD COLUMN IF NOT EXISTS safe_withdrawal_rate NUMERIC(6,4) NOT NULL DEFAULT 0.04;

ALTER TABLE isa_bridge_goal
  ADD COLUMN IF NOT EXISTS inflation_rate NUMERIC(6,4) NOT NULL DEFAULT 0.03;
